language: swift
osx_image: xcode10.3
xcode_workspace: Workflow.xcworkspace
xcode_scheme: Workflow
xcode_destination: platform=iOS Simulator,name=iPhone 8
if: tag IS blank
before_install:
- gem install cocoapods && pod install --repo-update
deploy:
  provider: script
  script: carthage build --no-skip-current && ./deploy_pod.sh
  on:
    branch: master
