name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-11
    env:
      working-directory: .github
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run TESTS
        run: bundle exec fastlane unit_test
        working-directory: ${{ env.working-directory }}
      - name: Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          fail_ci_if_error: true
      - name: Upload Test logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: ~/Library/Logs/scan
          retention-days: 90

  platform_test:
    runs-on: macos-11
    env:
      working-directory: .github
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Multiplatform TESTS
        run: bundle exec fastlane platform_test
        working-directory: ${{ env.working-directory }}

  cli_test:
    runs-on: macos-11
    env:
      working-directory: .github
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY  }}
      GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      MATCH_READONLY: true
    steps:
      - uses: actions/checkout@v2
      - name: Run CLI TESTS
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${MATCH_DEPLOY_KEY}"
          bundle exec fastlane CLI_test
        working-directory: ${{ env.working-directory }}

  build_for_swift_package_manager:
    runs-on: macos-11
    env:
      working-directory: .github
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Validate SwiftPM BUILDs
        run: bundle exec fastlane build_swiftpm
        working-directory: ${{ env.working-directory }}

  build_for_cocoapods:
    runs-on: macos-11
    env:
      working-directory: .github
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Validate Cocoapods Can Deploy (lib lint)
        run: bundle exec fastlane cocoapods_liblint
        working-directory: ${{ env.working-directory }}

  lint: 
    runs-on: macos-11
    env:
      working-directory: .github
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Swiftlint
        run: bundle exec fastlane lint
        working-directory: ${{ env.working-directory }}