name: CI

on: [ push, workflow_dispatch, pull_request ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run TESTS
        run: fastlane unit_test
      - name: Validate SwiftPM BUILDs
        run: | 
          cd Workflow
          swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios14.0-simulator"
          cd ..
      - name: Validate Cocoapods Can Deploy (lib lint)
        run: ./libLint.sh