name: CI

on: [ push, workflow_dispatch, pull_request ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run TESTS
        run: fastlane unit_test
      - name: SonarCloud Scan
        uses: mathrix-education/sonar-scanner@master
        with:
          version: 4.2.0.1873 # required
          scan: true
          args: --debug -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      - name: Validate SwiftPM BUILDs
        run: fastlane build_swiftpm
      - name: Validate Cocoapods Can Deploy (lib lint)
        run: cocoapods_liblint
      